/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/login/sms-code": {
    /**
     * 请求短信登录验证码
     * @description 通过短信登陆，支持给定用户名/手机号登录，若两个字段同时传递则优先按用户名寻找用户。
     */
    post: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      requestBody?: {
        content: {
          "application/x-www-form-urlencoded": {
            /**
             * @description 允许传入用户名或手机号
             * @example 18012345678
             */
            uname: string;
            /** @description captcha 验证成功的票据 */
            ticket: string;
            /** @description 本次验证的随机串，后续票据校验时需传递该参数 */
            randStr: string;
          };
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              success: boolean;
              /** @description 在登陆时需要传递的 tokenId */
              tokenId: string;
            };
          };
        };
      };
    };
  };
  "/register/{tokenId}": {
    /**
     * 验证码注册
     * @description 通过手机验证码注册用户
     */
    post: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
        path: {
          tokenId: string;
        };
      };
      requestBody?: {
        content: {
          "application/x-www-form-urlencoded": {
            /**
             * @description 发送的验证码，需要和token记录保持一致
             * @example 123456
             */
            verifyCode: string;
            /**
             * @description 用户名，不可包含中文和特殊字符，需要唯一
             * @example user123
             */
            uname: string;
            /**
             * Format: password
             * @description 密码，最短6位
             * @example pwd123
             */
            password: string;
            /**
             * @description 国籍/地区代码，符合ISO标准，默认为中国（zh）
             * @default zh
             * @example zh
             */
            nationality?: string;
            /**
             * @description 国内地区代码，若为国外则用00000代替（不显示）
             * @example 11000
             */
            regionCode?: string;
            /**
             * @description 用户角色枚举
             * @example 1
             * @enum {integer}
             */
            userRole?: 0 | 1 | 2 | 3 | 4;
            /**
             * Format: uint32
             * @description 用户年龄
             * @example 18
             */
            age?: number;
          };
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              success: boolean;
              code: number;
              /** @description 注册的用户 uid */
              uid: number;
            };
          };
        };
      };
    };
  };
  "/contest": {
    /**
     * 比赛列表
     * @description 分页的pageSize=20（数据库定义）
     */
    get: {
      parameters: {
        query?: {
          /**
           * @description 比赛规则，直接对应rule字段，一般不使用该参数（留空）
           * @example acm
           */
          rule?: "acm" | "oi" | "homework" | "ioi" | "ledo" | "strictioi";
          /**
           * @deprecated
           * @description 只查看分配给某个小组的比赛，一般不使用该参数（留空）
           * @example groupA
           */
          group?: string;
          /**
           * @description 分页
           * @example 1
           */
          page?: number;
          /**
           * @description 逗号分隔数组，查询比赛标签
           * @example a,b,c
           */
          tags?: string;
          /**
           * @description 查询比赛状态，对应左侧筛选条件（留空则查询全部）
           * @example incoming
           */
          category?: "incoming" | "ready" | "ongoing" | "done";
          /**
           * @description 模糊搜索值（开发中）
           * @example 测试比赛
           */
          q?: string;
          /**
           * @description 只查看已参加的比赛
           * @example true
           */
          attend?: boolean;
        };
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              /** 分页序号 */
              page: number;
              /** 页面总数 */
              tpcount: number;
              /** 查询条件 */
              qs: string;
              /**
               * 筛选规则
               * @deprecated
               * @description rule字段包含在了qs中，已废弃
               */
              rule: string;
              /** 比赛列表 */
              tdocs: components["schemas"]["Contest"][];
              tsdict: {
                [key: string]: Record<string, never>;
              };
              /**
               * 用户可用小组
               * @deprecated
               * @description 不会用到
               */
              groups: string;
              /**
               * 筛选组名
               * @deprecated
               * @description group包含在了qs中，已废弃
               */
              group: string;
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/record": {
    /** 获取评测记录列表 */
    get: {
      parameters: {
        query?: {
          /**
           * @description 默认为1
           * @example 1
           */
          page?: number;
          /**
           * @description 可以是pid或docId
           * @example P0001
           */
          pid?: string;
          /** @description 比赛的ObjectID */
          tid?: string;
          /** @example */
          uidOrName?: string;
          /**
           * @description 评测语言
           * @example cc.cc14o2
           */
          lang?: "cc.cc14o2" | "py.py3" | "scratch";
          /**
           * @description 评测状态
           * @example 1
           */
          status?: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 20 | 21 | 22 | 30 | 31 | 32 | 33;
          /**
           * @description 是否获取评测记录全部成员（默认为简略状态）
           * @example true
           */
          fullStatus?: boolean;
          /**
           * @description 是否获取全部记录（需要对应权限）
           * @example true
           */
          all?: boolean;
          /**
           * @description 是否获取全部域的记录（需要对应权限）
           * @example true
           */
          allDomain?: boolean;
        };
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
              /** 当前页码 */
              page: number;
              /** 所有评测记录 */
              rdocs: components["schemas"]["Record"][];
              tdoc: components["schemas"]["Contest"];
              pdict: {
                [key: string]: Record<string, never>;
              };
              udict: {
                [key: string]: {
                  "01HY63GX1S0DYHBD11ZQFC3F1E": string;
                };
              };
              /** @description 对应上面的筛选条件 */
              all: boolean;
              /** @description 对应上面的筛选条件 */
              allDomain: boolean;
              /** @description 对应上面的筛选条件 */
              filterPid: string;
              /** @description 对应上面的筛选条件 */
              filterTid: string;
              /** @description 对应上面的筛选条件 */
              filterUidOrName: string;
              /** @description 对应上面的筛选条件 */
              filterLang: string;
              /** @description 对应上面的筛选条件 */
              filterStatus: string;
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/tagsFilter/modify": {
    /**
     * 修改标签筛选器
     * @description 修改标签筛选器；
     * ** 这会影响所有题目标签在前端的可见性！ **
     */
    post: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      requestBody?: {
        content: {
          "multipart/form-data": {
            addFilter?: string;
            delFilter?: string;
          };
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/p": {
    /**
     * 首页题目筛选
     * @description 支持多条件并列筛选，默认留空的情况下直接读取题库题目；
     */
    get: {
      parameters: {
        query?: {
          /**
           * @description 默认值为1，分页参数
           * @example 1
           */
          page?: number;
          /**
           * @description 默认值为system_setting.pagination.problem
           * @example 15
           */
          limit?: number;
          /**
           * @description 逗号分隔数组，不需要括号包裹，请URLEncode
           * @example [
           *   "贪心算法,动态规划"
           * ]
           */
          tags?: string[];
          /**
           * @description 指定可用于提交题目的语言
           * @example scratch
           */
          lang?: string;
          /**
           * @description 默认为false，为true时只选择客观题
           * @example true
           */
          objective?: boolean;
          /**
           * @description 用于模糊搜索文本，可以与上面的条件一起使用（支持使用qs查询，但建议使用上面的接口）
           * @example 图形化
           */
          q?: string;
          /**
           * @description 指定从某个系统题单中查询符合上述条件的题目
           * @example 66200c489cd74d3e4c931302
           */
          source?: string;
        };
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              /** 当前页 */
              page: number;
              /** 总页数 */
              pcount: number;
              /**
               * 总题目数
               * @description 当前条件下的总题目数
               */
              ppcount: number;
              /**
               * 查找结果关系
               * @description 默认为eq即可，可忽略
               * @enum {string}
               */
              pcountRelation: "eq" | "gte";
              /** 题目 */
              pdocs: {
                /**
                 * 类型
                 * @description 题目docType=10
                 * @constant
                 */
                docType: 10;
                /** @description 题目真实ID是数字 */
                docId: number;
                /**
                 * PID
                 * @description 题目外显ID可以是pid，二者都可以寻址到题目
                 */
                pid: string;
                title: string;
                nSubmit: number;
                nAccept: number;
                tag: string[];
                hidden?: boolean;
                stats?: string;
                difficulty?: number;
                assign?: string[];
                config: string | components["schemas"]["ProblemConfig"];
                /** 摘要 */
                brief: string;
              }[];
              /** 题目用户状态字典 */
              psdict: {
                [key: string]: Record<string, never>;
              };
              /** 查询入参 */
              qs: string;
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
    /** 取消收藏题目 */
    post: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      requestBody?: {
        content: {
          "application/x-www-form-urlencoded": {
            /**
             * @description 操作名，Hydro特有的post魔法
             * @example unstar
             * @constant
             */
            operation: "unstar";
            /**
             * Format: uint32
             * @description 题目ID
             * @example 1
             */
            pid?: number;
          };
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/domain/group/code": {
    /**
     * 导出所有激活码数据
     * @description 需要用户有**编辑域**的权限
     */
    get: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
              groups: components["schemas"]["Group"][];
              tokens: components["schemas"]["ActivationToken"][];
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/captcha/test": {
    /**
     * 验证码（测试）
     * @description **仅在 debug 模式中可用**
     *
     * 测试验证码.
     */
    get: {
      parameters: {
        query: {
          /** @description 前端验证返回的 ticket */
          ticket: string;
          /** @description 前端验证返回的随机字符串 */
          randStr: string;
        };
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
              /** @description 验证是否成功 */
              success: boolean;
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/user/verify": {
    /**
     * 获取实名认证信息
     * @description 获取实名认证信息
     */
    get: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
              /** 身份证号 */
              idNumber: string;
              /** 真实姓名 */
              realName: string;
              /**
               * 是否通过验证
               * @description 是否通过了API校验
               */
              verified: boolean;
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
    /**
     * 上传实名信息
     * @description 上传实名信息（身份证号和姓名），在服务端调用第三方接口验证。
     */
    post: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      requestBody?: {
        content: {
          "application/x-www-form-urlencoded": {
            /** @example 110101200312133798 */
            idNumber: string;
            /** @example 张三 */
            realName: string;
          };
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
              success: boolean;
              code: number;
              idNumber: string;
              realName: string;
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/p-list": {
    /**
     * 获取所有系统题单
     * @description 以树状结构获取所有系统题单，用于首页的筛选树
     */
    get: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
              roots: components["schemas"]["SystemProblemList%20Recursive"][];
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/logout": {
    /**
     * 登出
     * @description 登出
     */
    post: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
            };
          };
        };
        /** @description Redirect */
        "x-200:Redirect": {
          content: {
            "application/json": {
              /** 重定向的URL */
              url: string;
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/problem/starred": {
    /** 获取收藏题目 */
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
        };
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
              pids: number[];
              psdict: {
                [key: string]: components["schemas"]["ProblemStatus"];
              };
              pdict: {
                [key: string]: components["schemas"]["Problem"];
              };
              page: number;
              pageSize: number;
              /** @description 总数 */
              psdocCount: number;
              /** @description 页数 */
              pageCount: number;
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/register/sms-code": {
    /**
     * 请求手机验证码
     * @description 获取手机验证码
     */
    post: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      requestBody?: {
        content: {
          "application/x-www-form-urlencoded": {
            /** @example 12345678900 */
            phoneNumber: string;
            /**
             * @description captcha 验证成功的票据
             * @example 123456
             */
            ticket: string;
            /** @description 本次验证的随机串，后续票据校验时需传递该参数 */
            randStr: string;
          };
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              success: boolean;
              code: number;
              tokenId: string;
            };
          };
        };
      };
    };
  };
  "/p-list/{tid}": {
    /**
     * 获取题单详情
     * @description 获取题单所有信息，包含内部所有题目、题目字典和是否有权限。
     */
    get: {
      parameters: {
        query?: {
          /**
           * @description 可选
           * @example 1
           */
          page?: number;
          /**
           * @description 可选
           * @example 15
           */
          pageSize?: number;
        };
        header?: {
          /** @example application/json */
          Accept?: string;
        };
        path: {
          /** @description 题单docId */
          tid: string;
        };
      };
      requestBody?: {
        content: {
          "application/x-www-form-urlencoded": Record<string, never>;
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
              tdoc: components["schemas"]["SystemProblemList"];
              /** @description 题目字典，用于pid查询对应的详情 */
              pdict: {
                [key: string]: Record<string, never>;
              };
              /** @description 是否有该题单的权限 */
              hasPermission: boolean;
              page: number;
              pageSize: number;
              pageCount: number;
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
    /**
     * 获取题单中上一题
     * @description 获取题单中的上一题
     */
    post: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
        path: {
          /** @description 题单docId */
          tid: string;
        };
      };
      requestBody?: {
        content: {
          "application/x-www-form-urlencoded": {
            /**
             * @description 操作名，Hydro特有的post魔法
             * @example prev
             * @constant
             */
            operation: "prev";
            /**
             * @description 当前PID
             * @example 1
             */
            curPid: string;
          };
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
              /** @description 目标题目id */
              pid: number;
              /** @description 是否有对应题目权限 */
              access: boolean;
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/record/{rid}": {
    /** 获取题目评测详情 */
    get: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
        path: {
          rid: string;
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
              udoc: components["schemas"]["User"];
              rdoc: components["schemas"]["Record"];
              pdoc: components["schemas"]["Problem"];
              tdoc?: components["schemas"]["Contest"] | null;
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/contest/{tid}": {
    /** 比赛详情 */
    get: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
        path: {
          /**
           * @description 比赛ID
           * @example 660fb4f221e13d71de96129a
           */
          tid: string;
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              tdoc: components["schemas"]["Contest"];
              /** 用户状态 */
              tsdoc: {
                /** ObjectID */
                _id: string;
                /** @description 关联的DocID */
                docId: string;
                /** @description 关联的DocType */
                docType: number;
                /** 域ID */
                domainId: string;
                /** 用户ID */
                uid: number;
                /**
                 * 是否参加
                 * @default null
                 * @enum {integer}
                 */
                attend?: 1 | 0;
                /**
                 * 参加时间
                 * Format: date-time
                 */
                startAt?: string;
              };
              /**
               * 用户字典
               * @description 用于owner的显示
               */
              udict: {
                [key: string]: Record<string, never>;
              };
              /** 比赛相关文件 */
              files: components["schemas"]["FileInfo"][];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
    /**
     * 报名比赛
     * @description **自带实名认证**，无需手动请求
     */
    post: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
        path: {
          tid: string;
        };
      };
      requestBody?: {
        content: {
          "application/x-www-form-urlencoded": {
            /**
             * @description 操作名，Hydro特有的post魔法
             * @example attend
             * @constant
             */
            operation: "attend";
            /**
             * @description 比赛邀请码，可选
             * @example abcde
             */
            code?: string;
          };
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Redirect */
        "x-200:Redirect": {
          content: {
            "application/json": {
              /** 重定向的URL */
              url: string;
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/login/{tokenId}": {
    /** 短信验证码登录 */
    post: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
        path: {
          tokenId: string;
        };
      };
      requestBody?: {
        content: {
          "application/x-www-form-urlencoded": {
            /**
             * @description 短信验证码
             * @example 123456
             */
            verifyCode: string;
            /**
             * @description 长期记忆session
             * @default false
             * @example true
             */
            rememberme?: boolean;
            /**
             * @description 登陆后跳转url
             * @example /
             */
            redirect?: string;
          };
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
            };
          };
        };
        /** @description Redirect */
        "x-200:Redirect": {
          content: {
            "application/json": {
              /** 重定向的URL */
              url: string;
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/priv": {
    /**
     * 激活指定组权限
     * @description 使用激活码激活指定组权限
     */
    post: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      requestBody?: {
        content: {
          "application/x-www-form-urlencoded": {
            /**
             * @description 操作名，Hydro特有的post魔法
             * @example activate
             * @constant
             */
            operation: "activate";
            /**
             * @description 激活码（6位）
             * @example aaaaa
             */
            code: string;
            /**
             * @description UID（留空则使用session值）
             * @example 1
             */
            uid?: number;
          };
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
              success: boolean;
              /**
               * 组名
               * @description 激活的小组名称
               */
              group: string;
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/bulletin": {
    /** 查询公告列表 */
    get: {
      parameters: {
        query?: {
          /**
           * @description 分页，为空时不分页
           * @example 1
           */
          page?: number;
          /**
           * @description 分页大小，默认为server.bulletin.limit
           * @example 15
           */
          limit?: number;
          /**
           * @description 筛选的标签，为空时展示全部
           * @example a,b,c
           */
          tags?: string;
        };
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
              bdocs: components["schemas"]["BulletinDoc"][];
              /** @description 按当前limit的page数量 */
              bdocsPage: number;
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/register/email-code": {
    /**
     * 请求邮箱验证码
     * @description 获取邮箱验证码
     */
    post: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      requestBody?: {
        content: {
          "application/x-www-form-urlencoded": {
            /** @example {% mock 'email' %} */
            mail: string;
            /**
             * @description captcha 验证成功的票据
             * @example 123456
             */
            ticket: string;
            /** @description 本次验证的随机串，后续票据校验时需传递该参数 */
            randStr: string;
          };
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              success: boolean;
              code: number;
              tokenId: string;
            };
          };
        };
      };
    };
  };
  "/p/{pid}": {
    /** 获取题目详情 */
    get: {
      parameters: {
        query?: {
          /**
           * @description 比赛ID（如果有的话）
           * @example abcedefg
           */
          tid?: string;
          /**
           * @deprecated
           * @description pjax请求（已废弃）
           * @example false
           */
          pjax?: boolean;
        };
        header?: {
          /** @example application/json */
          Accept?: string;
        };
        path: {
          /**
           * @description 题目ID
           * @example 1
           */
          pid: string;
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
              /** 题目信息 */
              pdoc: {
                /**
                 * 类型
                 * @description 题目docType=10
                 * @constant
                 */
                docType: 10;
                /** @description 题目真实ID是数字 */
                docId: number;
                /**
                 * PID
                 * @description 题目外显ID可以是pid，二者都可以寻址到题目
                 */
                pid: string;
                title: string;
                content: string;
                nSubmit: number;
                nAccept: number;
                tag: string[];
                /**
                 * 数据文件
                 * @description 题目数据（如输入、输出等）
                 */
                data: components["schemas"]["FileInfo"][];
                /** 其他文件 */
                additional_file: components["schemas"]["FileInfo"][];
                hidden?: boolean;
                /** @description 是否为HTML格式 */
                html?: boolean;
                difficulty?: number;
                /** @description 题目用于排序的字段 */
                sort?: string;
                reference?: {
                  domainId: string;
                  pid: number;
                };
                assign?: string[];
                config: string | components["schemas"]["ProblemConfig"];
                /** 摘要 */
                brief: string;
              };
              udoc: components["schemas"]["User"];
              /**
               * 题目状态
               * @description 无tid时为null
               */
              psdoc: components["schemas"]["ProblemStatus"] | null;
              /** 题目标题 */
              title: string;
              /**
               * 总题解数
               * Format: uint32
               */
              solutionCount: number;
              /**
               * 总讨论数
               * Format: uint32
               */
              discussionCount: number;
              /**
               * 比赛信息
               * @description 仅在存在tid时才会有值
               */
              tdoc?: {
                /**
                 * 比赛标签
                 * @description 用于筛选比赛
                 */
                tag: string[];
                /**
                 * 报名开始时间
                 * Format: date-time
                 */
                checkinBeginAt: string;
                /**
                 * 报名结束时间
                 * Format: date-time
                 */
                checkinEndAt: string;
                /** 封面图 */
                imageURL: string;
                /** 是否需要实名 */
                needRealName: boolean;
                /** @description ObjectID */
                _id: string;
                /** @description ObjectID */
                docId: string;
                /**
                 * 类型
                 * Format: uint32
                 * @description 30=比赛 32=系统题单
                 * @enum {integer}
                 */
                docType: 30 | 31 | 32 | 40;
                /**
                 * 开始日期
                 * Format: date-time
                 * @description 比赛/作业的开放日期（题单不受此影响）
                 */
                beginAt: string;
                /**
                 * 结束日期
                 * Format: date-time
                 */
                endAt: string;
                /** 参加人数 */
                attend: number;
                /** 标题 */
                title: string;
                /** 说明内容 */
                content: string;
                /**
                 * 规则
                 * @description 比赛规则（赛制），homework为特殊规则
                 * @enum {string}
                 */
                rule: "acm" | "oi" | "homework" | "ioi" | "ledo" | "strictioi";
                /** 题目 */
                pids: number[];
                /** 是否排名 */
                rated?: boolean;
                _code?: string;
                /**
                 * 分配给
                 * @description 若只分配给特定小组，则只有特定组有权限访问（与权限组结合）
                 */
                assign?: string[];
                files?: components["schemas"]["FileInfo"][];
                allowViewCode?: boolean;
                /**
                 * 锁定日期
                 * Format: date-time
                 * @description 仅用于比赛
                 */
                lockAt?: string;
                /**
                 * 是否解封
                 * @description 仅用于比赛
                 */
                unlocked?: boolean;
                /**
                 * 自动隐藏
                 * @description 不在日期内自动隐藏，仅用于比赛（schedule实现）
                 */
                autoHide?: boolean;
                /** @description 仅用于比赛 */
                balloon?: {
                  [key: string]: string;
                };
                /**
                 * 参与者得分
                 * @description 仅用于比赛
                 */
                score?: {
                  [key: string]: number;
                };
                /**
                 * 比赛时长
                 * @description 单位为小时，仅用于比赛
                 */
                duration: number;
                /**
                 * 惩罚起始时间
                 * Format: date-time
                 * @description 仅用于作业
                 */
                penaltySince?: string;
                /** 拥有者UID */
                owner: number;
              };
              /**
               * 比赛所有者信息
               * @description 仅在存在tid时才会有值（在所有者请求时会返回null）
               */
              owner_udoc?: components["schemas"]["User"] | null;
              rdoc?: components["schemas"]["Record"];
              /** 相关比赛 */
              ctdocs: components["schemas"]["Contest"][];
              /** 相关作业 */
              htdocs: components["schemas"]["Contest"][];
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
    /**
     * 检查题目权限
     * @description 检查题目是否可被当前用户访问，若不能则提供可选的激活方式。
     */
    post: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
        path: {
          pid: string;
        };
      };
      requestBody?: {
        content: {
          "application/x-www-form-urlencoded": {
            /**
             * @description 操作名，Hydro特有的post魔法
             * @example check
             * @constant
             */
            operation?: "check";
          };
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
              /** 是否有权限访问 */
              hasPerm: boolean;
              /**
               * 可用的激活途径
               * @description 仅在hasPerm=false时才会返回ways
               */
              activation?: ("group" | "point")[];
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/bulletin/tags": {
    /**
     * 获取可用公告标签
     * @description 获取告示栏上方的标签列表
     */
    get: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
              bulletinTags: string[];
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/login": {
    /** 使用sid续约登录 */
    get: {
      parameters: {
        query?: {
          /**
           * @description Cookie中返回的SessionID
           * @example U81Z9oOEONRlynLYIoRPVn13Sj10l3Om
           */
          sid?: string;
        };
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
    /**
     * 用户名&密码登录
     * @description 使用用户名和密码登录
     */
    post: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      requestBody?: {
        content: {
          "application/x-www-form-urlencoded": {
            /** @example {{admin_uname}} */
            uname: string;
            /** @example {{admin_pwd}} */
            password: string;
          };
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
            };
          };
        };
        /** @description Redirect */
        "x-200:Redirect": {
          content: {
            "application/json": {
              /** 重定向的URL */
              url: string;
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/p/{pid}/submit": {
    /**
     * 提交评测
     * @description 客观题和编程题使用相同的接口提交
     * 对于客观题的答案使用yaml编码，写入code字段中
     * 格式如下：
     * ```yaml
     * '1': '2'
     * '2':
     *   - C
     * '3':
     *   - A
     *   - B
     *   - C
     *   - D
     * ```
     */
    post: {
      parameters: {
        query?: {
          /**
           * @description 比赛ObjectID
           * @example abcd
           */
          tid?: string;
        };
        header?: {
          /** @example application/json */
          Accept?: string;
        };
        path: {
          pid: string;
        };
      };
      requestBody?: {
        content: {
          "application/x-www-form-urlencoded": {
            /**
             * @description 提交语言
             * @example py.py3
             * @enum {string}
             */
            lang: "cc.cc14o2" | "py.py3" | "scratch" | "_";
            /**
             * @description 代码内容
             * @example print('Hello World')
             */
            code?: string;
            /**
             * @description 是否为比赛统一评测，若为统一评测则返回tid，否则返回rid
             * @example true
             */
            pretest?: boolean;
            input?: string;
            /** @description 比赛ID，用于将评测记录关联到指定比赛记录 */
            tid?: string;
          };
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
              /** 跳转URL */
              url: string;
              /**
               * 评测记录ID
               * @description 非集中评测模式返回rid
               */
              rid?: string;
              /**
               * 比赛ID
               * @description 集中评测模式返回tid
               */
              tid?: string;
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/bulletin/{bid}": {
    /** 获取公告详情 */
    get: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
        path: {
          /** @description BulletinID */
          bid: string;
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
              bdoc: components["schemas"]["BulletinDoc"];
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/contest/{tid}/problems": {
    /**
     * 获取比赛题单
     * @description 未加入、未开始的比赛会抛出错误；首次访问会被视为参加了比赛，会添加`startAt`记录
     */
    get: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
        path: {
          tid: string;
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              pdict: {
                [key: string]: components["schemas"]["Problem"];
              };
              psdict: {
                [key: string]: components["schemas"]["ProblemStatus"];
              };
              udict: {
                [key: string]: components["schemas"]["User"];
              };
              rdict: {
                [key: string]: components["schemas"]["Record"];
              };
              tdoc: components["schemas"]["Contest"];
              tsdoc: components["schemas"]["ContestStatus"];
              tcdocs: string[];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
              /** @description 是否展示得分 */
              showScore: boolean;
              /** @description 是否可以查看记录详情 */
              canViewRecord: boolean;
              rdocs: components["schemas"]["Record"][];
              [key: string]: Record<string, never>;
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/domain/group/{gid}/code": {
    /**
     * 获取小组所有的激活码
     * @description 【要求域编辑权限】在域管理面板中编辑小组时，可以通过该接口获取特定组的激活码。
     */
    get: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
        path: {
          /** @example 660f57076cdd0d8ef6fa4349 */
          gid: string;
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
              group: components["schemas"]["Group"];
              /** @description 所有激活码 */
              tokens: string[];
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
    /**
     * 新增激活码
     * @description 给指定小组生成指定数量的激活码
     */
    post: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
        path: {
          gid: string;
        };
      };
      requestBody?: {
        content: {
          "application/x-www-form-urlencoded": {
            /**
             * Format: date-time
             * @description 激活码过期时间
             * @example 2024-04-23T12:49:00.308Z
             */
            expireAt: string;
            /**
             * @description 允许使用次数（默认为1）
             * @default 1
             * @example 1
             */
            times?: number;
            /**
             * @description 激活码所属机构名
             * @example admin
             */
            owner?: string;
            /**
             * @description 生成数量，默认为1
             * @default 1
             * @example 1
             */
            genNum?: number;
          };
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Redirect */
        "x-200:Redirect": {
          content: {
            "application/json": {
              /** 重定向的URL */
              url: string;
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
              success: boolean;
              /** @description 生成的激活码 */
              data: components["schemas"]["ActivationToken"][];
            };
          };
        };
      };
    };
  };
  "/bulletin/create": {
    /**
     * 创建新公告
     * @description 创建一个新公告
     */
    post: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      requestBody?: {
        content: {
          "application/x-www-form-urlencoded": {
            /**
             * @description 操作名，Hydro特有的post魔法
             * @example update
             * @constant
             */
            operation: "update";
            /** @example 测试公告 */
            title: string;
            /**
             * @description In markdown
             * @example 123456
             */
            content: string;
            /**
             * @description 标签，用英文逗号 "," 分割
             * @example a,b,c
             */
            tags: string;
          };
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
              success: boolean;
              /** @description 新添加的公告 ID */
              docId: string;
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/bulletin/{bid}/edit": {
    /** 删除公告 */
    post: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
        path: {
          /** @example 6660c5b2a19931b7d9bfd231 */
          bid: string;
        };
      };
      requestBody?: {
        content: {
          "application/x-www-form-urlencoded": {
            /**
             * @description 操作名，Hydro特有的post魔法
             * @example delete
             * @constant
             */
            operation: "delete";
          };
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
              success: boolean;
            };
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              /** @description 错误信息 */
              error: components["schemas"]["Error"];
              UiContext: components["schemas"]["UiContext"];
              UserContext: components["schemas"]["UserContext"];
            };
          };
        };
      };
    };
  };
  "/user/lostpass": {
    /**
     * 请求找回密码
     * @description 请求找回密码
     */
    post: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      requestBody?: {
        content: {
          "application/x-www-form-urlencoded": {
            /**
             * @description 邮箱或手机号
             */
            emailOrPhone: string;
          };
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
              tokenId: string;
            };
          };
        };
      };
    };
  };
  "/user/lostpass/with_code": {
    /**
     * 验证输入验证码正确性
     * @description 验证输入验证码正确性
     */
    post: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      requestBody?: {
        content: {
          "application/x-www-form-urlencoded": {
            /**
             * @description 邮箱或手机号
             */
            emailOrPhone: string;
            /**
             * @description 输入的验证码
             */
            verifyCode: string;
            tokenId: string;
          };
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
              success: boolean;
              tokenId: string;
            };
          };
        };
      };
    };
  };
  "/user/lostpass/reset": {
    /**
     * 重设用户密码
     * @description 重设用户密码
     */
    post: {
      parameters: {
        header?: {
          /** @example application/json */
          Accept?: string;
        };
      };
      requestBody?: {
        content: {
          "application/x-www-form-urlencoded": {
            tokenId: string;
            /**
             * @description 新密码
             */
            password: string;
          };
        };
      };
      responses: {
        /** @description 成功 */
        200: {
          content: {
            "application/json": {
              UserContext: components["schemas"]["UserContext"];
              UiContext: components["schemas"]["UiContext"];
              success: boolean;
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    "SystemProblemList Recursive": {
      /**
       * 父节点
       * @description ObjectID
       */
      parent: string;
      /** 子节点数组 */
      children: components["schemas"]["SystemProblemList%20Recursive"][];
      /** @description ObjectID */
      _id: string;
      /** @description ObjectID */
      docId: string;
      /**
       * 类型
       * Format: uint32
       * @description 30=比赛 32=系统题单
       * @enum {integer}
       */
      docType: 30 | 31 | 32 | 40;
      /**
       * 开始日期
       * Format: date-time
       * @description 比赛/作业的开放日期（题单不受此影响）
       */
      beginAt: string;
      /**
       * 结束日期
       * Format: date-time
       */
      endAt: string;
      /** 标题 */
      title: string;
      /** 说明内容 */
      content: string;
      /**
       * 规则
       * @description 比赛规则（赛制），homework为特殊规则
       * @enum {string}
       */
      rule: "acm" | "oi" | "homework" | "ioi" | "ledo" | "strictioi";
      /** 题目 */
      pids: number[];
      /**
       * 分配给
       * @description 若只分配给特定小组，则只有特定组有权限访问（与权限组结合）
       */
      assign?: string[];
      /** 拥有者UID */
      owner: number;
    };
    BulletinDoc: {
      _id: string;
      docId: string;
      docType: number;
      domainId: string;
      maintainer: number[];
      title: string;
      /** 标签 */
      tags: string[];
      /**
       * 内容
       * @description Markdown 格式，前端需渲染
       */
      content: string;
      owner: number;
      postAt: number;
    };
    SubtaskResult: {
      /** @enum {string} */
      type: "min" | "max" | "sum";
      score: number;
      status: number;
    };
    TestCase: {
      id?: number;
      subtaskId?: number;
      score?: number;
      time: number;
      memory: number;
      status: number;
      message: string;
    };
    JudgeMessage: {
      message: string;
      params?: string[];
      stack?: string;
    };
    Record: {
      /**
       * ID
       * @description ObjectId
       */
      _id: string;
      /** 域ID */
      domainId: string;
      /** 对应题目ID */
      pid: number;
      /** 提交用户ID */
      uid: number;
      /** 提交语言 */
      lang: string;
      /** 代码 */
      code: string;
      /** 得分 */
      score: number;
      /** 使用内存（KB） */
      memory: number;
      /** 评测用时 */
      time: number;
      /** 评测信息 */
      judgeTexts: (string | components["schemas"]["JudgeMessage"])[];
      /** 编译信息 */
      compilerTexts: string[];
      /** 测试用例 */
      testCases: components["schemas"]["TestCase"][];
      /** 是否是重新评测 */
      rejudged: boolean;
      source?: string;
      /** @description judge uid */
      judger: number;
      /**
       * 评测时间
       * Format: date-time
       */
      judgeAt: string;
      /** 状态码 */
      status: number;
      /** 进度 */
      progress?: number;
      /** @description pretest & hack */
      input?: string;
      /**
       * 比赛ID
       * @description ObjectId
       */
      contest?: string;
      /** 文件字典 */
      files?: {
        [key: string]: string;
      };
      /**
       * 子任务结果
       * @description 有些题目配置了子任务，这里可以查看其运行结果
       */
      subtasks?: {
        [key: string]: components["schemas"]["SubtaskResult"];
      };
    };
    /** UDict */
    UserDict: {
      [key: string]: Record<string, never>;
    };
    Contest: {
      /** @description ObjectID */
      _id: string;
      /** @description ObjectID */
      docId: string;
      /**
       * 类型
       * Format: uint32
       * @description 30=比赛 32=系统题单
       * @enum {integer}
       */
      docType: 30 | 31 | 32 | 40;
      /**
       * 开始日期
       * Format: date-time
       * @description 比赛/作业的开放日期（题单不受此影响）
       */
      beginAt: string;
      /**
       * 结束日期
       * Format: date-time
       */
      endAt: string;
      /** 参加人数 */
      attend: number;
      /** 标题 */
      title: string;
      /** 说明内容 */
      content: string;
      /**
       * 规则
       * @description 比赛规则（赛制），homework为特殊规则
       * @enum {string}
       */
      rule: "acm" | "oi" | "homework" | "ioi" | "ledo" | "strictioi";
      /** 题目 */
      pids: number[];
      /** 是否排名 */
      rated?: boolean;
      _code?: string;
      /**
       * 分配给
       * @description 若只分配给特定小组，则只有特定组有权限访问（与权限组结合）
       */
      assign?: string[];
      files?: components["schemas"]["FileInfo"][];
      allowViewCode?: boolean;
      /**
       * 锁定日期
       * Format: date-time
       * @description 仅用于比赛
       */
      lockAt?: string;
      /**
       * 是否解封
       * @description 仅用于比赛
       */
      unlocked?: boolean;
      /**
       * 自动隐藏
       * @description 不在日期内自动隐藏，仅用于比赛（schedule实现）
       */
      autoHide?: boolean;
      /** @description 仅用于比赛 */
      balloon?: {
        [key: string]: string;
      };
      /**
       * 参与者得分
       * @description 仅用于比赛
       */
      score?: {
        [key: string]: number;
      };
      /**
       * 比赛时长
       * @description 单位为小时，仅用于比赛
       */
      duration: number;
      /**
       * 惩罚起始时间
       * Format: date-time
       * @description 仅用于作业
       */
      penaltySince?: string;
      /** 拥有者UID */
      owner: number;
      /**
       * 比赛标签
       * @description 用于筛选比赛
       */
      tag: string[];
      /**
       * 报名开始时间
       * Format: date-time
       */
      checkinBeginAt: string;
      /**
       * 报名结束时间
       * Format: date-time
       */
      checkinEndAt: string;
      /** 封面图 */
      imageURL: string;
      /** 是否需要实名 */
      needRealName: boolean;
    };
    ContestStatus: {
      /** ObjectID */
      _id: string;
      /** @description 关联的DocID */
      docId: string;
      /** @description 关联的DocType */
      docType: number;
      /** 域ID */
      domainId: string;
      /** 用户ID */
      uid: number;
      /**
       * 是否参加
       * @default null
       * @enum {integer}
       */
      attend?: 1 | 0;
      /**
       * 参加时间
       * Format: date-time
       */
      startAt?: string;
      journal: {
        /** 评测记录ID */
        rid: string;
        /** 题目ID */
        pid: number;
        /**
         * 评测状态
         * @enum {integer}
         */
        status: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 20 | 21 | 22 | 30 | 31 | 32 | 33;
        score: number;
        subtasks: {
          [key: string]: {
            /** @enum {string} */
            type: "sum" | "min" | "max";
            score: number;
            /** @enum {integer} */
            status: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 20 | 21 | 22 | 30 | 31 | 32 | 33;
          };
        };
      }[];
      /** 得分 */
      score: number;
    };
    StatusBaseDoc: {
      /** ObjectID */
      _id: string;
      /** @description 关联的DocID */
      docId: string;
      /** @description 关联的DocType */
      docType: number;
      /** 域ID */
      domainId: string;
      /** 用户ID */
      uid: number;
    };
    Document: {
      _id: string;
      docId: string;
      docType: number;
      domainId: string;
      owner: number;
      maintainer: number[];
    };
    ProblemStatus: {
      _id: string;
      docId: number;
      /** @constant */
      docType: 10;
      domainId: string;
      uid: number;
      rid?: string;
      score?: number;
      status?: number;
      nSubmit?: number;
      nAccept?: number;
      star?: boolean;
    };
    Problem: {
      /**
       * 类型
       * @description 题目docType=10
       * @constant
       */
      docType: 10;
      /** @description 题目真实ID是数字 */
      docId: number;
      /**
       * PID
       * @description 题目外显ID可以是pid，二者都可以寻址到题目
       */
      pid: string;
      title: string;
      content: string;
      nSubmit: number;
      nAccept: number;
      tag: string[];
      /**
       * 数据文件
       * @description 题目数据（如输入、输出等）
       */
      data: components["schemas"]["FileInfo"][];
      /** 其他文件 */
      additional_file: components["schemas"]["FileInfo"][];
      hidden?: boolean;
      /** @description 是否为HTML格式 */
      html?: boolean;
      stats?: string;
      difficulty?: number;
      /** @description 题目用于排序的字段 */
      sort?: string;
      reference?: {
        domainId: string;
        pid: number;
      };
      assign?: string[];
      config: string | components["schemas"]["ProblemConfig"];
      /** 摘要 */
      brief: string;
    };
    ProblemConfig: {
      redirect?: string[];
      count: number;
      memoryMax: number;
      memoryMin: number;
      timeMax: number;
      timeMin: number;
      langs?: string[];
      type: string;
      subType?: string;
      target?: string;
      hackable?: boolean;
    };
    SystemProblemList: {
      /**
       * 父节点
       * @description ObjectID
       */
      parent: string;
      /** 子节点数组 */
      children: string[];
      /** @description ObjectID */
      _id: string;
      /** @description ObjectID */
      docId: string;
      /**
       * 类型
       * Format: uint32
       * @description 30=比赛 32=系统题单
       * @enum {integer}
       */
      docType: 30 | 31 | 32 | 40;
      /**
       * 开始日期
       * Format: date-time
       * @description 比赛/作业的开放日期（题单不受此影响）
       */
      beginAt: string;
      /**
       * 结束日期
       * Format: date-time
       */
      endAt: string;
      /** 标题 */
      title: string;
      /** 说明内容 */
      content: string;
      /**
       * 规则
       * @description 比赛规则（赛制），homework为特殊规则
       * @enum {string}
       */
      rule: "acm" | "oi" | "homework" | "ioi" | "ledo" | "strictioi";
      /** 题目 */
      pids: number[];
      /**
       * 分配给
       * @description 若只分配给特定小组，则只有特定组有权限访问（与权限组结合）
       */
      assign?: string[];
      /** 拥有者UID */
      owner: number;
    };
    FileInfo: {
      _id: string;
      name: string;
      size: number;
      etag: string;
      /** Format: date-time */
      lastModified: string;
    };
    ContestBase: {
      /** @description ObjectID */
      _id: string;
      /** @description ObjectID */
      docId: string;
      /**
       * 类型
       * Format: uint32
       * @description 30=比赛 32=系统题单
       * @enum {integer}
       */
      docType: 30 | 31 | 32 | 40;
      /**
       * 开始日期
       * Format: date-time
       * @description 比赛/作业的开放日期（题单不受此影响）
       */
      beginAt: string;
      /**
       * 结束日期
       * Format: date-time
       */
      endAt: string;
      /** 参加人数 */
      attend: number;
      /** 标题 */
      title: string;
      /** 说明内容 */
      content: string;
      /**
       * 规则
       * @description 比赛规则（赛制），homework为特殊规则
       * @enum {string}
       */
      rule: "acm" | "oi" | "homework" | "ioi" | "ledo" | "strictioi";
      /** 题目 */
      pids: number[];
      /** 是否排名 */
      rated?: boolean;
      _code?: string;
      /**
       * 分配给
       * @description 若只分配给特定小组，则只有特定组有权限访问（与权限组结合）
       */
      assign?: string[];
      files?: components["schemas"]["FileInfo"][];
      allowViewCode?: boolean;
      /**
       * 锁定日期
       * Format: date-time
       * @description 仅用于比赛
       */
      lockAt?: string;
      /**
       * 是否解封
       * @description 仅用于比赛
       */
      unlocked?: boolean;
      /**
       * 自动隐藏
       * @description 不在日期内自动隐藏，仅用于比赛（schedule实现）
       */
      autoHide?: boolean;
      /** @description 仅用于比赛 */
      balloon?: {
        [key: string]: string;
      };
      /**
       * 参与者得分
       * @description 仅用于比赛
       */
      score?: {
        [key: string]: number;
      };
      /**
       * 比赛时长
       * @description 单位为小时，仅用于比赛
       */
      duration: number;
      /**
       * 惩罚起始时间
       * Format: date-time
       * @description 仅用于作业
       */
      penaltySince?: string;
      /**
       * 惩罚规则
       * @description 仅用于作业
       */
      penaltyRules?: Record<string, never>;
      /** 拥有者UID */
      owner: number;
    };
    Error: {
      /** 错误信息 */
      message: string;
      /**
       * 参数
       * @description 错误参数，一般可以填入错误信息中的模板插值占位符
       */
      params: string[];
      /**
       * 错误堆栈
       * @description 服务端的错误堆栈信息
       */
      stack: string;
    };
    Group: {
      _id: string;
      domainId: string;
      name: string;
      uids: number[];
      /**
       * 父节点
       * @description 父节点的ObjectId
       */
      parent?: string | null;
      children?: string[] | null;
      activation?: string[];
    };
    ActivationToken: {
      _id: string;
      updateIp?: string;
      updateUa?: string;
      createIp?: string;
      createUa?: string;
      createHost?: string;
      /** @description 枚举类型，激活码Type=10 */
      tokenType: number;
      /** @description 日期ISO String */
      createAt: string;
      /** @description 日期ISO String */
      updateAt?: string;
      /** @description 日期ISO String */
      expireAt: string;
    };
    User: {
      _id?: number;
      mail?: string;
      mailLower?: string;
      uname?: string;
      unameLower?: string;
      hash?: string;
      salt?: string;
      hashType?: string;
      regat?: string;
      ip?: string[];
      loginat?: string;
      loginip?: string;
      priv?: number;
      avatar?: string;
      nationality?: string;
      age?: number;
      oier?: boolean;
      nickname?: string;
    };
    Domain: {
      _id?: string;
      name?: string;
      /** @description 域名称的小写版 */
      lower?: string;
      /** @description UID */
      owner?: number;
      /** @description 系统公告 */
      bulletin?: string;
      /** @description 域内权限组定义 */
      roles?: {
        /** @description 访客权限 */
        guest?: string;
        /** @description 登录用户权限 */
        default?: string;
        [key: string]: string | undefined;
      };
      /** @description 域头像URL */
      avatar?: string;
      /** @description 允许的编程语言（逗号分隔） */
      langs?: string;
      share?: string;
      [key: string]: unknown;
    };
    UiContext: {
      /** @description 系统设置中定义，请求静态资源时前缀 */
      cdn_prefix: string;
      /** @description 系统设置中定义，服务器URL前缀 */
      url_prefix: string;
      /** @description 系统设置中定义，web socket前缀 */
      ws_prefix: string;
      domainId: string;
      domain: components["schemas"]["Domain"];
    };
    UserContext: {
      authn: boolean;
      uname: string;
      mail: string;
      gender: string;
      avatar: string;
      avatarUrl: string;
      backgroundImage: string;
      loginat: string;
      regat: string;
      fontFamily: string;
      theme: string;
      timeZone: string;
      codeLang: string;
      codeFontFamily: string;
      formatCode: boolean;
      monacoTheme: string;
      preferredEditorType: string;
      hashType: string;
      tfa: boolean;
      groups: string[];
      perm: string;
      priv: number;
      role: string;
      rpInfo: {
        key1: string;
        key2: string;
      };
      scope: string;
      domains: string[];
      pinnedDomains: string[];
      _id: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
